Remove platform from VoidGenerator by default
CloudburstMC/Cloudburst pull request #115
Opened 2021-04-04 16:40 UTC by rtm516

This disables the stone platform generated using the VoidGenerator unless the generator options are `enablePlatform`.

2021-04-05 13:35 UTC, DaMatrix requested changes
would be nice if the options were a JSON object or something, to allow for more options to be added in the future

2021-04-17 20:08 UTC, SupremeMortal commented
Yes JSON would be the best option since that's what Bedrock saves in its `level.dat` for vanilla presets however this can be a temp fix till that is implemented.

2021-04-17 20:08 UTC, SupremeMortal approved these changes

2021-04-19 10:23 UTC, DaMatrix approved these changes
alright then

2021-04-19 10:24 UTC, merged

2021-04-19 10:25 UTC, DaMatrix commented
oh, c'mon, of *course* i didn't notice that the CI check failed...